# Welcome to the Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64 )

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [4]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [5]:
myarr[0,1]

6

In [6]:
myarr[0,2]

32

In [7]:
myarr[0,3]

7

In [8]:
myarr[0,0]

3

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0,2]=48

In [12]:
myarr

array([[ 3,  6, 48,  7]], dtype=int64)

**Array Creation: Conversion from other Python Structures**

In [13]:
listarray =np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,23,25})

array({25, 34, 23}, dtype=object)

**Intrinsic NumPy array creation functions**

In [18]:
zeroes=np.zeroes((3,3))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [19]:
zeroes=np.zeros((3,3))

In [20]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeroes.dtype

dtype('float64')

In [22]:
rng=np.arange(10)

In [23]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
lspace=np.linspace (1,5,10)

In [25]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
emp=np.empty((2,3))

In [27]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307]])

In [28]:
emp_like=np.empty_like(listarray)

In [29]:
emp_like

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [6357084, 7143524, 7209065]])

In [30]:
ide=np.identity(10)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
arr=np.arange(99)

In [33]:
arange

NameError: name 'arange' is not defined

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr=arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr=arr.ravel()

In [41]:
arr.shape

(99,)

In [42]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [43]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [44]:
ar=np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.sum(axis=0)

array([12,  8,  9])

In [47]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [48]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [49]:
ar.flat

In [50]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

36

In [54]:
one=np.array([1,3,4,652])

In [55]:
one

array([  1,   3,   4, 652])

In [56]:
one.argmax()

3

In [57]:
one.add(14)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [58]:
one.arhmin()

AttributeError: 'numpy.ndarray' object has no attribute 'arhmin'

In [59]:
one.argmin()

0

In [60]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [61]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [62]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [63]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [64]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [65]:
ar2=np.array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [66]:
ar2

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [67]:
ar+ar2

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [68]:
 np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [69]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [70]:
np.sum(ar)

29

In [71]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [73]:
import sys

In [74]:
py_ar= [0,4,55,2]

In [75]:
np_arr=np.array(py_ar)

In [76]:
sys.getsizeof(1) * len(py_ar)

112

In [80]:
np_arr.itemsize * np_arr.size

16

In [81]:
np_arr.tolist()

[0, 4, 55, 2]

In [82]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [85]:
ar.type()

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [86]:
type(ar)

numpy.ndarray

In [87]:
d=np.full((3,3),6)

In [88]:
d

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [89]:
ar.dot(ar2)

array([[14, 32,  9],
       [32, 77, 33],
       [ 9, 33, 50]])